
name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}"

      - name: Determine version bump
        id: determine_version
        run: |
          if [[ "$(gh pr view ${{ github.event.pull_request.number }} --json labels -q ".labels[].name")" == *"major"* ]]; then
            echo "version=major" >> $GITHUB_OUTPUT
          elif [[ "$(gh pr view ${{ github.event.pull_request.number }} --json labels -q ".labels[].name")" == *"minor"* ]]; then
            echo "version=minor" >> $GITHUB_OUTPUT
          else
            echo "version=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        run: |
          version=${{ steps.determine_version.outputs.version }}
          git config user.email "leandrotomasjofre@gmail.com"
          git config user.name "Leandro Jofre"
          git tag -a "v$(date +%Y%m%d%H%M%S)-${version}" -m "Version bump to ${version}"
          git push origin --tags

      - name: Get PR details
        id: pr_details
        uses: actions/github-script@v3
        with:
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pr.data;

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.determine_version.outputs.version }}
          release_name: SillyTavern-QOL ${{ steps.determine_version.outputs.version }}
          body: |
           ## What's new in this release?
           - **PR Title**: ${{ steps.pr_details.outputs.title }}
           - **Merged by**: ${{ steps.pr_details.outputs.user.login }}
           - **Changes**: ${{ steps.pr_details.outputs.body }}
          draft: false
          prerelease: false
